version: '3'
services:
  prisma:
    image: registry.gitlab.com/e-venture/cp-backend:latest
    networks:
      - web
    labels:
      - traefik.enabled=true
      - traefik.backend=prisma
      - traefik.frontend.rule=Host:api.eval.chartr.me
      - traefik.docker.network=web
      - traefik.port=4000
    restart: always

networks: web:
